# Generated by Django 4.1.7 on 2023-02-22 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_department_userlist_create_time_userlist_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlist",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.department",
                verbose_name="部门",
            ),
        ),
    ]
