# Generated by Django 4.1.7 on 2023-02-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_userlist_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlist",
            name="department",
        ),
    ]
