# Generated by Django 4.1.7 on 2023-02-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_userlist_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="手机号")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "一级"), (2, "二级"), (3, "二级"), (4, "二级"), (5, "二级")],
                        default=1,
                        verbose_name="等级",
                    ),
                ),
                ("status", models.BooleanField(default=False, verbose_name="状态")),
                ("price", models.IntegerField(default=99, verbose_name="价格")),
            ],
        ),
    ]
