# Generated by Django 4.1.7 on 2023-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_alter_phonenumber_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "以售卖"), (2, "待售卖")], default=2, verbose_name="状态"
            ),
        ),
    ]
