# Generated by Django 4.1.7 on 2023-02-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_alter_phonenumber_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=32, verbose_name="admin account"),
                ),
                ("password", models.CharField(max_length=64, verbose_name="password")),
            ],
        ),
    ]
